select cmh.header_id          头ID,
       cmh.organization_id    组织ID,
       cmh.req_number         单号,
       cmh.req_date           申请日期,
       cmh.status             状态,
       cmh.dispositions_id    ,
       cmh.department_id      部门ID,
       cmh.wf_item_key        ,
       cmh.inv_type           ,
       cmh.attribute_category ,
       cmh.remark             ,
       cmh.to_org_id ,
       cmh.to_organization_id,
       cmh.org_id,
       cmh.hr_dept_id,
       cmh.hr_dept,
       cmh.approver_id,
       cmh.require_hr_name	  HR姓名,
       cmh.require_hr_empnum  HR工号,
       cmh.require_hr_dept    HR部门,
       cmh.require_hr_deptnum HR部门编号,
       cmh.in_flag,
       cmh.out_flag,
       cmh.transfer_status    抛转状态
  from cux.cux_inv_material_headers cmh 
 where cmh.header_id = 447488
