create or replace view cux_ready_item_sum_v as
select cri.organization_id,
       ood.organization_code,
       ood.organization_name,
       cri.doc_no,
       cri.doc_type,
       cri.doc_date,
       cri.doc_status,
       cri.wip_entity_id,
       cri.wip_entity_name,
       cri.primary_item_id,
       msi.segment1 primary_item_code,
       msi.description primary_item_desc,
       cri.supply_subinventory,
       cri.now_qty,
       CRI.TRANSFER_STATUS transfer_status_code,
       cri.to_sub,
       cri.is_over,
       cri.is_print,
       cri.operation_code,
       cri.attribute3,
       cri.created_by
  from cux_ready_item               cri,
       org_organization_definitions ood,
       mtl_system_items_vl          msi
 where 1=1
   and cri.organization_id=ood.organization_id
   and msi.organization_id=cri.organization_id
   and msi.inventory_item_id=cri.primary_item_id
 group by cri.organization_id,
           ood.organization_code,
           ood.organization_name,
           cri.doc_no,
           cri.doc_type,
           cri.doc_date,
           cri.doc_status,
           cri.wip_entity_id,
           cri.wip_entity_name,
           cri.primary_item_id,
           msi.segment1,
           msi.description,
           cri.supply_subinventory,
           cri.now_qty,
           TRANSFER_STATUS,
           cri.to_sub,
           cri.is_over,
           cri.is_print,
           cri.operation_code,
           cri.attribute3,
           cri.created_by;
